name: Quotly Cleanup Staging Images

on:
  workflow_dispatch:

permissions: read-all

jobs:
  cleanup:
    runs-on: self-hosted
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up old staging images
        run: |
          chmod +x cleanup_docker_images.sh
          ./cleanup_docker_images.sh ${{ github.repository_owner }} quotly-staging ${{ secrets.QUOTLY_TOKEN }} 5